# ============================================================================
#  Yazi Configuration
# ============================================================================

[manager]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

[preview]
tab_size = 2
max_width = 600
max_height = 900

